### ISSUE TITLE
COPY in the dockerfile leaves around an image, try using alternative volume.

### ISSUE THREAD

**Issue by rosskevin** [alienfast/docker-rails#14]
We know that compose host volumes for the project are at least 2x slower based on testing, and that they cause files to be written as `root` #5 .

Switching to using `COPY` in the dockerfile gets us the performance we expect, but we can see that the image with our original source code sticks around:

``` bash
$ docker images
REPOSITORY                      TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
111_web                         latest              3e607a2c2664        2 days ago          842 MB
```

Look at using volumes, perhaps similar to gems to get same performance without a duplicate/lingering image of an old build.

Perhaps this isn't an issue, and the `REPOSITORY` name is just misleading, as build `112` just layers over `111_web`, I'm not sure yet.

**Comment by rosskevin** [comment]
https://docs.docker.com/v1.6/compose/yml/#volumes

To get the equivalent performance of a [Dockerfile `VOLUME` like mysql uses](https://github.com/docker-library/mysql/blob/5836bc9af9deb67b68c32bebad09a0f7513da36e/5.6/Dockerfile#L40), Perhaps this means we:
1. Declare a `volumes: - /project` in the compose yaml
2. Do a readonly host mount of the source i.e. `.:/source_project:ro`
3. Immediately exec a copy in the web container `cp /source_project /project`
4. Then allow it to startup.

This seems brittle...

**Comment by rosskevin** [comment]
A data volume is a specially-designated directory within one or more containers that **bypasses the Union File System**

https://docs.docker.com/userguide/dockervolumes/

**Comment by rosskevin** [comment]
Trying to initialize a data volume container (that will get automatically cleaned up) and just reference it via compose, implementing the copy inside the image:

``` yaml
  project:
    image: busybox
    command: bash -c "cp -r /source_project/* /project/."
    volumes:
      - /project
      - .:/source_project:ro

  web:
    build: .
    working_dir: /project/spec/dummy
    ports:
      - "3000"

    links:
      - db

    volumes_from:
      # Mount the gems data volume container for cached bundler gem files
      - #{DOCKER_RAILS_GEMS_VOLUME_NAME}
      - project
```
