### ISSUE TITLE
Automate gemset volume entries GEM_HOME and volumes_from

### ISSUE THREAD

**Issue by rosskevin** [alienfast/docker-rails#20]
Since we are going to automate/seed for ssh-agent forwarding, we might as well do the same for the gemset, it reduces config.

New syntax in docker-rails.yml

``` yaml
# create a global gemset to be shared amongst all ruby 2.2.2 containers.
gemset:
  name: 2.2.2
  # setup GEM_HOME environment variable and `volumes_from` to mount the global gemset container
  containers:
    - web
```

Generates a seed default config of 

``` yaml
compose:
  web:
    environment:
      # Tell bundler where to get the files
      - GEM_HOME=/gemset/2.2.2

    volumes_from:
      # Mount the gems data volume container for cached bundler gem files
      - gemset-2.2.2
```
