### ISSUE TITLE
Distinguish compose -p build by project name + target environment.

### ISSUE THREAD

**Issue by rosskevin** [alienfast/docker-rails#7]
Containers currently created are something like `1_web_1` with the default `build` of `1`.  Given that we want to be concurrent-friendly, running `development` and `test` with the default build would have a conflict.

**Comment by rosskevin** [comment]
Some problem for concurrent projects, project `foo` and project `bar` have indistinguishable container names, so we should likely string in the project name as well i.e. directory name.  Does `1_web_1` belong to `foo` or `bar`?

**Comment by rosskevin** [comment]
Looks like compose is sanitizing `-p`, so `-p acme_test_333` turns into web container `acmetest333_web_1`, which messes up finding these containers by name later.

**Comment by rosskevin** [comment]
One way to do this could be to use [`labels`](https://github.com/docker/compose/blob/master/docs/yml.md#labels), but we would have to discover all services and inject them for each container:

i.e.

``` yaml
labels:
  com.alienfast.docker-rails.build: 333
  com.alienfast.docker-rails.project: acme_foo_long_unsanitized
  com.alienfast.docker-rails.target: test
```

There is a related discussion here https://github.com/docker/compose/issues/1518 

Injecting labels would allow us to look up the container, but still, when running `docker ps`, the container name is almost jibberish.  https://github.com/docker/compose/issues/2119
